### ISSUE TITLE
net::ERR_CERT_AUTHORITY_INVALID when loading the screenshot on the front page

### ISSUE THREAD

**Issue by James103** [tvanprooyen/mbm#1]
Currently (2020-11-14), the screenshot with all the new blocks added does not load when embedded into the front page for the mod. The only way to view the image is to either open up the image in a new tab or download the image and open it in any image viewing software.

When attempting to load the image, Chrome 86 reports to the console:
`GET https://tylervp.com/mbm/ScreenShots/CurrentBlocks.png net::ERR_CERT_AUTHORITY_INVALID`

The same error applies for all images from `https://tylervp.com` which automatically redirects to `http://tylervp.com`.

**Comment by tvanprooyen** [comment]
Fixed the current blocks image, working on the other images

**Comment by tvanprooyen** [comment]
Fixed images in comments that I was allowed to edit, Thank you for letting me know about this issue. I'm now closing this issue as it is fixed.
