### ISSUE TITLE
Purple Textures In Inventory - Roughly Enough Items (REI)

### ISSUE THREAD

**Issue by jimmytrouser** [tvanprooyen/mbm#13]
For some reason the textures are purple & black for some items in this mod, see image below:

![2021-03-01_12 10 48](https://user-images.githubusercontent.com/7896905/109498707-bf180f80-7a8b-11eb-994f-b2a5fa8eaea5.png)
![2021-03-01_12 10 52](https://user-images.githubusercontent.com/7896905/109498723-c4755a00-7a8b-11eb-8549-852a68c4a330.png)

However, when I place them they are fine:

![2021-03-01_12 11 00](https://user-images.githubusercontent.com/7896905/109498747-cb9c6800-7a8b-11eb-89b4-69985e1b1588.png)
![2021-03-01_12 11 04](https://user-images.githubusercontent.com/7896905/109498757-d0f9b280-7a8b-11eb-8203-04c3d4d50d8e.png)

The tooltip is still purple and black though:

![2021-03-01_12 11 09](https://user-images.githubusercontent.com/7896905/109498781-da831a80-7a8b-11eb-994c-74ac0f8d3114.png)

If I only put this mod in my pack then it's fine; I have 200 or so mods so it will take me a long time to check what is causing this.  Before I do this any ideas?

I have Lithium & Phosphorus installed and they are not the problem as I have checked this; I also do not have sodium installed.

What can I do to check what is causing this without checking all 200 mods? 

Moreblock version 0.1.4
Minecraft 1.16.5
Fabric API 0.31.0
Mod loader 0.11.2

**Comment by tvanprooyen** [comment]
I'll have to look at the difference between some of the model files

**Comment by jimmytrouser** [comment]
I managed to narrow it down to the linking books mod, specifically Cardinal Components API that is needed for it to work.

Hope that helps.

**Comment by tvanprooyen** [comment]
Let me know if your still having an issue with this, Thanks!
