### ISSUE TITLE
[Feature request] Add a config for disabling vertical slabs.

### ISSUE THREAD

**Issue by RDKRACZ** [tvanprooyen/mbm#14]
The reason for this - there is a [mod](https://www.curseforge.com/minecraft/mc-mods/full-slabs) that allows for vertical placements of any slabs so your variants, sorry for this, aren't needed. Full slabs has this advantage where you don't need another crafting recipe because you just craft a slab and you can place it both horizontally and vertically.

**Comment by tvanprooyen** [comment]
Vertical Slabs Disabled added 0.2.1a

add mbmconfig.json to the mods folder with this as the contents

{
  "vslabsEnabled": false
}

"vslabsEnabled": true - Means vertical slabs are enabled
"vslabsEnabled": false - Means vertical slabs are disabled

**Comment by tvanprooyen** [comment]
Command added- /mbmgamerules verticalslabsenabled [true|false]

This will automatically create the file and set the value in file. Also changes the value when command is run at any time.
