### ISSUE TITLE
Server Side crash in 1.6-beta (1.16.5) more blocks mod

### ISSUE THREAD

**Issue by Mysticpasta1** [tvanprooyen/mbm#19]
[crash-2021-07-05_20.25.09-server.txt](https://github.com/tvanprooyen/mbm/files/6766711/crash-2021-07-05_20.25.09-server.txt)

this crashes on first start of the modpack

**Comment by tvanprooyen** [comment]
See if it crashes with the 0.1.7-b. I tested it before it was released, and didn't have any loading issues
