### ISSUE TITLE
No more updates?

### ISSUE THREAD

**Issue by RDKRACZ** [tvanprooyen/mbm#20]
Is this mod abandoned?

**Comment by tvanprooyen** [comment]
Nope, just have a lot of personal things come up. Hopefully ill be back at it again soon

**Comment by tvanprooyen** [comment]
![2021-09-05_09 14 20](https://user-images.githubusercontent.com/4705130/132128277-0d51ebea-16ab-463c-bc57-546da3aa4210.png)

Almost all done, just a few problems with rendering

**Comment by tvanprooyen** [comment]
Rendering issues fixed, now in testing features.

**Comment by RDKRACZ** [comment]
Downloaded from CF, will test later. Thanks!

**Comment by RDKRACZ** [comment]
Can you also update your repo with the latest code? Also, in the readme, it says MC 1.16 etc.

**Comment by tvanprooyen** [comment]
repo updated

**Comment by RDKRACZ** [comment]
Hi, I noticed the repo is out of date - on the CurseForge the latest release is from Nov 15, but the last commit here is from Oct 2. Asking mainly because you added many new blocks and I wanted to optimize assets again. Tested it and the size goes down from 2,7 MB to 1,9 MB.
(Decided to comment here instead of opening a new issue)

**Comment by tvanprooyen** [comment]
Working on updating it now

**Comment by tvanprooyen** [comment]
Updated! Thanks!
