### ISSUE TITLE
Rename modid.mixins.json.

### ISSUE THREAD

**Issue by RDKRACZ** [tvanprooyen/mbm#21]
It should use your namespace instead of the example one.

**Comment by tvanprooyen** [comment]
oh... this file must have been carried over by accident. It doesn't effect the code in any way. I'll delete it.

**Comment by RDKRACZ** [comment]
I think you forgot to update the license file here on GitHub because the one in the jar from the curseforge is different

**Comment by tvanprooyen** [comment]
Your indeed right, the one from github is correct.

**Comment by tvanprooyen** [comment]
License updated
