### ISSUE TITLE
Recipe conflict between blocks

### ISSUE THREAD

**Issue by Friskygote** [tvanprooyen/mbm#25]
Hello, as I've been doing my pull requests I've noticed that cobblestone bricks and large cobblestone have same recipe (4 cobblestones in a square) which is causing a conflict. 
I don't have a real suggestion on new recipe that would make sense however.

**Comment by tvanprooyen** [comment]
Is this in conflicts with another mod?

**Comment by Friskygote** [comment]
Oh god yes, I'm an idiot, I thought I double checked but modes are so similar in name that I actually thought they were the same. My bad.

**Comment by tvanprooyen** [comment]
Changed large cobble stone bricks recipe now its 9 cobblestone will output 9 large cobblestone
