### ISSUE TITLE
Lanterns unable to attach to bottoms of blocks.

### ISSUE THREAD

**Issue by ShockinglySane** [tvanprooyen/mbm#26]
As the issue title says, with this mod enabled I seem to be unable to hang lanterns off the bottoms of blocks any longer, except for if I hang them off of the newly added "rope" block. It seems that lanterns are now set to ONLY hang off rope.

**Comment by tvanprooyen** [comment]
Issue fixed. Not sure how it happened, but it must have changed while conversation. This will be in the 0.1.8 update. Thank you!

**Comment by tvanprooyen** [comment]
I looked at the old code. When fabric updated some mappings and functions, the waterlogged field was named LanternBlock.field_26441. When I was going though and updating the errors, I must have thought it was for hanging field.

**Comment by tvanprooyen** [comment]
![2021-09-10_02 41 28](https://user-images.githubusercontent.com/4705130/132811858-b2b75630-237f-468e-a65e-f88f537c6113.png)
