### ISSUE TITLE
Iron Block issues

### ISSUE THREAD

**Issue by Friskygote** [tvanprooyen/mbm#27]
Hello, hopefully this time I'm not mixing up another mod by accident ._.
Iron blocks do not have a tool specified and because of that destroying them doesn't drop any items. I expected pickaxes to be the tool needed to mine them out. Additionally I expected Iron Blocks to be used as a base for Beacon blocks however I don't think they are being recognized? Perhaps adding them to beacon_base_blocks tag would help (didn't test that).

**Comment by tvanprooyen** [comment]
That's a good idea, and I found out the other day while playing on my survival world that it didn't drop anything either. I ended up fixing it for the next update. Hardened iron doesn't drop anything either. That's a great idea to add it to the beacon base blocks tag

**Comment by tvanprooyen** [comment]
Added iron blocks to the beacon base tag file. Its all set for 0.1.8 update

**Comment by tvanprooyen** [comment]
0.1.8-a is out for testing on curse forge
