### ISSUE TITLE
Launcher Crash - Mod Incompatibility??

### ISSUE THREAD

**Issue by Toilet-Man** [tvanprooyen/mbm#28]
Just installed the mod in my mod pack and the game doesn't boot up.

Here is the crash log,
[launcher_log.txt](https://github.com/tvanprooyen/mbm/files/7157046/launcher_log.txt)

I'm not too sure but I think this is the error you'll be searching for:
`Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [modid.mixins.json:ExampleMixin] from phase [DEFAULT] in config [modid.mixins.json] FAILED during PREPARE`

Also it says "`Exception in thread "main" java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kambrik'!`" but I uninstalled Kambrik and its related mod (Bountiful)

Lemme know if you think you found the issue I'd be glad to hear about it <3

**Comment by tvanprooyen** [comment]
It's looking for a file "ExampleMixin.java" as directed by the modid.mixins.json file. Moreblocks mod uses the file moreblocksmod.mixin.json. They probably forgot to remove the example mixin files and forgot to remove it from the directed path from the fabric.mod.json file. It will take me a second to locate the issue in the log file. Ill let you know what I come up with. 

I do have 0.1.8 Alpha released on curse forge, its the most up to date one. There are still some bug fixes being worked on when minecraft updated from 1.6.5 to 1.7.1

`{
  "required": true,
  "minVersion": "0.8",
  "package": "com.tylervp.mixin",
  "compatibilityLevel": "JAVA_16",
  "mixins": [
    "LeavesBlockMixin",
    "MelonBlockMixin",
    "CauldronBlockMixin",
    "LanternBlockMixin",
    "DeadBushMixin",
    "AxeItemMixin",
    "DefaultBiomeFeaturesMixin",
    "BlockMixin",
    "ShovelMixin",
    "WallBlockMixin",
    "PaneBlockMixin",
    "PlantBlockMixin",
    "GrassBlockMixin"
  ],
  "client": [
  ],
  "injectors": {
    "defaultRequire": 1
  }
}
`

**Comment by tvanprooyen** [comment]
Can you send me a zip file of the mods installed?

**Comment by tvanprooyen** [comment]
Also if you could let me know what mods you have recently added/updated before encountering this problem, besides mbm.

**Comment by Toilet-Man** [comment]
> Can you send me a zip file of the mods installed?
Yeah sure

> Also if you could let me know what mods you have recently added/updated before encountering this problem, besides mbm.
Absolutely, I sort all my modpack updates. Thing is, I added your mod (mbm) in my lastest update so I don't think it'll help to get the recently added mods

**Comment by Toilet-Man** [comment]
> Can you send me a zip file of the mods installed?

Here
https://drive.google.com/file/d/1_o4Tzb-an4VtFLF-38zsdNevvi-n8iwR/view?usp=sharing

**Comment by tvanprooyen** [comment]
I updated MBM to 0.1.8 bata, check if this is still giving you issues?
