### ISSUE TITLE
Lantern blocks cannot be hanged from full blocks

### ISSUE THREAD

**Issue by Friskygote** [tvanprooyen/mbm#30]
As title, I tried hanging lantern blocks in my base however were unable to do so. 
To test if it was this mod causing the issue I've commented out https://github.com/tvanprooyen/mbm/blob/main/src/main/java/com/tylervp/mixin/LanternBlockMixin.java#L37L53 this overwrite and compiled the mod. Lanterns could then be hanged from the blocks. (don't know how these things work enough to make a PR with actual fix and retain mod feature compatibility)
Tested with version of mod currently in the repo.

**Comment by tvanprooyen** [comment]
I fixed it already in 0.1.8 bata, someone else noted the issue #26

**Comment by Friskygote** [comment]
Oh sorry then, somehow missed that, damn.
