### ISSUE TITLE
A lot of errors

### ISSUE THREAD

**Issue by TheButterbrotMan** [tvanprooyen/mbm#32]
https://bytebin.lucko.me/N6rofqpWKy

**Comment by TheButterbrotMan** [comment]
1.18.2, 0.13.3, Fabric

**Comment by TheButterbrotMan** [comment]
This is causing a lot of missing textures.

**Comment by tvanprooyen** [comment]
Is this still an issue? I haven't experienced it yet, are there anything else that is being loaded? And do you have the fabric api loaded with the mod?
