### ISSUE TITLE
Add curseforge and github links to the fabric.mod.json.

### ISSUE THREAD

**Issue by RDKRACZ** [tvanprooyen/mbm#9]
I couldn't find your mod on the curseforge because in-game it's called More Blocks Mod but on the curseforge, it's MBM More Blocks Mod and because curseforge is a shitty broken website if you search for "More Blocks Mod" your mod will not display. Btw can you upload to the [Modrinth](https://modrinth.com)?

**Comment by tvanprooyen** [comment]
That's a great idea, honestly I didn't think about posting this to different mod sites. I'll see if I can try to fix the search on curseforge

**Comment by tvanprooyen** [comment]
Added links to curseforge, modrinth, and github.
Added Mod to Modrinth under the URL https://modrinth.com/mod/mbm.

Unfortunately couldn't find a way to improve curseforge search for More Blocks Mod. I was hoping to find some sort of keyword optimization, but they have nothing.

**Comment by tvanprooyen** [comment]
Update Submitted as 0.1.4-b
